name: Merge upstream branches
on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '5 */6 * * *'
jobs:
  v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge upstream
        run: |
          git config --global user.name 'i207m'
          git config --global user.email 'i207m@users.noreply.github.com'

          git remote add upstream https://github.com/ddiu8081/chatgpt-demo.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
  v2:
    needs: v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge upstream
        run: |
          git config --global user.name 'i207m'
          git config --global user.email 'i207m@users.noreply.github.com'

          git remote add upstream https://github.com/ddiu8081/chatgpt-demo.git
          git fetch upstream

          git checkout --track origin/feat/v2
          git merge --no-edit upstream/feat/v2
          git push origin feat/v2
